fix(ADA-1612): Removed generic role
kaltura/playkit-js-ui-managers pull request #62
Opened 2024-09-04 09:46 UTC by RazvanBrinzoiK05

With:
https://github.com/kaltura/playkit-js-common/pull/61

Issue:
Generic role is for use by user agents and not by developers, so it must be removed

Fix:
Providing null as a valid prop that will remove the role attribute making the html element generic without developer intervention that can be detected in the developer console.

2024-09-04 11:54 UTC, semarche-kaltura requested changes
PR can be merged once playkit-js-common version got upgraded

2024-09-06 07:56 UTC, RazvanBrinzoiK05 commented
Updated the PR with the common repo version

2024-09-19 07:38 UTC, semarche-kaltura requested changes

2024-09-19 07:38 UTC, semarche-kaltura commented on package.json
> +    "@playkit-js/common": "^1.5.18"
yarn.lock file changes missed

2024-09-19 09:17 UTC, semarche-kaltura approved these changes

2024-09-26 10:28 UTC, merged