fix(ADA-1734): Continues ADA-1500, Converting JSX labels to string
kaltura/playkit-js-ui-managers pull request #63
Opened 2024-09-27 10:37 UTC by RazvanBrinzoiK05

**With:**
- Plugins involved:
https://github.com/kaltura/playkit-js-share/pull/54
https://github.com/kaltura/playkit-js-info/pull/104
https://github.com/kaltura/playkit-js-downloads/pull/73
https://github.com/kaltura/playkit-js-moderation/pull/95

**Issue:**:
Previous JSX was not translated when loaded in the ui-managers
This was causing aria-label to be rendered: [Object object]:
![image](https://github.com/user-attachments/assets/aecff15e-77a8-4534-96cb-e258e7bc5319)

 
**Fix**:
Added Localizer for the plugins
Used "preact-render-to-string" library to convert the JSX to string

**Question**:
Installing the library generated also these files:
playkit-ui-managers.js
playkit-ui-managers.js.map
Should I add them to the PR as well ?

2024-09-29 07:06 UTC, SivanA-Kaltura commented
@RazvanBrinzoiK05 Not sure i understand the use case here

2024-09-30 11:49 UTC, SivanA-Kaltura requested changes

2024-09-30 11:49 UTC, SivanA-Kaltura commented on package-lock.json
> +{
please remove this file as we use yarn for dependency management

2024-09-30 12:11 UTC, RazvanBrinzoiK05 commented
This PR will be closed and the issue will be continued here: 
https://github.com/kaltura/playkit-js-ui-managers/pull/64

2024-09-30 12:11 UTC, closed without merging