fix(FEC-12132): Add documentation
kaltura/playkit-js-ui-managers pull request #8
Opened 2022-06-14 11:53 UTC by JonathanTGold

### Description of the Changes

Add documentation and update types

solves: FEC-12132

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2022-06-16 10:58 UTC, SivanA-Kaltura requested changes

2022-06-16 10:58 UTC, SivanA-Kaltura commented on docs/guide.md
> +Add the ui-managers to the setup config like any other plugin in addition to the plugin uses the ui-managers.
```suggestion
Add the ui-managers plugin configuration object to the player plugins configuration.
```

2022-06-16 10:58 UTC, SivanA-Kaltura commented on docs/guide.md
> +get and use the desired service using the player's api inside the loadMedia() hook of your plugin
```suggestion
You can access and use the desired service by using the player's api inside the loadMedia() hook of your plugin.
```

2022-06-16 10:58 UTC, SivanA-Kaltura commented on README.md
> +- ###Side Panels
```suggestion
- Side Panels
```

2022-06-16 10:58 UTC, SivanA-Kaltura commented on README.md
> +  manages and controls the side panel items\
```suggestion
  Manages and controls the side panel items, including:\
```

2022-06-16 10:58 UTC, SivanA-Kaltura commented on README.md
> +  that's includes:
```suggestion
```

2022-06-16 10:58 UTC, SivanA-Kaltura commented on README.md
> +  - Automatically deactivates a panel when its counter panel is activated\
```suggestion
  - When a panel is activated, its counter panel is automatically deactivated.\
```

2022-06-16 10:58 UTC, SivanA-Kaltura commented on README.md
> +- ###Upper bar manager
```suggestion
- Upper bar manager
```

2022-06-16 10:58 UTC, SivanA-Kaltura commented on README.md
> +  manages and controls the upper bar menu\
```suggestion
  Manages and controls the upper bar menu, including:\
```

2022-06-16 10:58 UTC, SivanA-Kaltura commented on README.md
> +  that's includes:
```suggestion
```

2022-06-16 10:58 UTC, SivanA-Kaltura commented on README.md
> +  - sets the order icons are shown.
```suggestion
  - Setting the order in which icons are shown.
```

2022-06-16 10:58 UTC, SivanA-Kaltura commented on README.md
> +  - Increases and decreases the number of icons that appear depending on the size of the player\
```suggestion
  - Increasing and decreasing the number of icons that appear depending on the size of the player.\
```

2022-06-16 10:58 UTC, SivanA-Kaltura commented on README.md
> +  - When an item is activated in the panel, the other items are automatically deactivated in that panel.
```suggestion
  - When an item is activated in a panel, the other items in that panel are automatically deactivated.
```

2022-06-16 10:58 UTC, SivanA-Kaltura commented on README.md
> +Each service manages a different area of UI functionality
```suggestion
Each service manages a different area of UI functionality.
```

2022-06-16 10:58 UTC, SivanA-Kaltura commented on docs/guide.md
> +# usage guide
```suggestion
# Usage guide
```

2022-06-23 13:20 UTC, JonathanTGold commented on docs/guide.md
> +Add the ui-managers to the setup config like any other plugin in addition to the plugin uses the ui-managers.
fixed

2022-06-23 13:41 UTC, JonathanTGold commented on README.md
> +  manages and controls the side panel items\
fix

2022-06-23 13:41 UTC, JonathanTGold commented on README.md
> +  that's includes:
fixed

2022-06-23 13:44 UTC, JonathanTGold commented on README.md
> +  - Increases and decreases the number of icons that appear depending on the size of the player\
fixed

2022-06-23 13:47 UTC, JonathanTGold commented on README.md
> +  - When an item is activated in the panel, the other items are automatically deactivated in that panel.
fixed

2022-06-23 13:47 UTC, JonathanTGold commented on README.md
> +Each service manages a different area of UI functionality
fixed

2022-06-23 13:48 UTC, JonathanTGold commented on docs/guide.md
> +# usage guide
fixed

2022-06-23 14:37 UTC, SivanA-Kaltura commented on README.md
> +- ###Side Panels
a space is missing between the number signs and the text

2022-06-29 08:05 UTC, SivanA-Kaltura approved these changes

2022-07-18 11:18 UTC, merged